services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    networks:
      - civitas_network

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - civitas_network
volumes:
  postgres_data:

networks:
  civitas_network:
    driver: bridge
