on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Civitas Deployment / Udev-it
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          debug: true
          script: /usr/local/bin/deploy-agent/deploy-agent.sh
